IdWL = false -- TRUE PARA USAR O ID DA WL COM O ELEMENTDATA / FALSE PARA USAR O SEU SISTEMA DE ID 

ElementDataID = "ID" -- COLOQUE AQUI O ELEMENTDATA DO ID QUE VOCÊ QUER NO SEU SERVER // 

Sigla = "SUA SIGLA" -- COLOQUE A SIGLA DO SEU SERVIDOR


--------------------- AVISO !!!! ------------ 
-- CASO COLOQUE TRUE, VOCÊ TERÁ QUE TER APENAS O SISTEMA DE TAG NA CABEÇA DO ID